server:
  port: 8083

spring:
  #应用名称
  application:
    name: demo-consumer

dubbo:
  application:
    name: demo-consumer
    qos-enable: false
  registry:
    address: zookeeper://192.168.22.131:2181
  scan:
    base-packages: com.demo.consumer
